import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";

import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./components/provider/ToasterProvider";
import LogInModal from "./components/modals/LogInModal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";

const inter = Inter({ subsets: ["latin"] });

export const  metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser({children});
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <SearchModal />
        <RentModal />
        <LogInModal />
        <RegisterModal />
        <NavBar currentUser={currentUser}></NavBar>
    
        <div className="pb-20 pt-28">
        {children}
        </div>
        </body>
    </html>
  );
}
